updated read-me with instructions on how to run app
georgelzeng/EABWebsite-S19 pull request #86
Opened 2019-05-10 01:47 UTC by quichey

also removed extraneous edit.html.haml file in root directory

2019-05-10 22:41 UTC, mihizi commented
Why did you delete edit.html.haml? 😨

2019-05-10 23:01 UTC, georgelzeng commented on README.rdoc
> +
Also needs block for SUPERADMIN_CODE

2019-05-10 23:02 UTC, georgelzeng-zz requested changes
One last item

2019-05-10 23:02 UTC, georgelzeng commented on README.rdoc
> +
Also needs space for SUPERADMIN_CODE

2019-05-11 00:27 UTC, quichey commented
to mihir: I deleted an edit.html.haml that was created in the root directory. It was mistakenly created by me while i was in atom. The original edit.html.haml still exists.

2019-05-11 00:35 UTC, quichey commented on README.rdoc
> +
good catch. added

2019-05-11 16:09 UTC, georgelzeng-zz approved these changes
all g

2019-05-11 16:10 UTC, merged